### ISSUE TITLE
 mdatp-devicecontrol 

### ISSUE THREAD

**Issue by castelan91** [microsoft/mdatp-devicecontrol#13]
device_control_policy_schema.json throws errors with the object type when I tried to use on JAMF

**Comment by bryan-lipinski** [comment]
device_control_policy_schema.json is not intended to be used with JAMF directly.  The schema is to enable users to validate the v2 Device Control policy JSON prior to deployment with JAMF using a site like https://www.jsonschemavalidator.net/. 

The v1 policy was directly embedded within the MDE Settings as described [here](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-device-control-overview?view=o365-worldwide).   This made things fairly complicated in a few ways.

The v2 implementation takes a different approach adding one level of indirection.  The v2 policy JSON can be copied as a string into the 'Device Control'\'Policy' preference in the MDE Preferences configuration profile.  The new 'Policy' field has already been added to [schema.json](https://github.com/microsoft/mdatp-xplat/blob/master/macos/schema/schema.json) in the mdatp-xplat repo to make this even simpler.
