### ISSUE TITLE
Azure AD Group SID

### ISSUE THREAD

**Issue by tinman613** [microsoft/mdatp-devicecontrol#3]
Hello all...

I am trying to use an Azure AD group SID for an allow option and it does not work.
I have used my local user SID to verify the rule syntax and it worked ok.

Any idea's?
Thanks

**Comment by MatthewWhiteMoJ** [comment]
What local SID did you use - i have tried to use the local user SID from one workstation but that is not common across AADJ devices or have you used the AAD User object SID to test with?

**Comment by tewchen** [comment]
The AAD group Sid is still in Private Preview. currently only support Local or AD group sid
