### ISSUE TITLE
any updates available?

### ISSUE THREAD

**Issue by sakthiskumar** [microsoft/mdatp-devicecontrol#5]
Hi, I am currently working on project to enable the device control using GPOs and the documentation / steps is not clear / complete. Will there be any updates to this in near future?

**Comment by tewchen** [comment]
We updated the document (https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control?view=o365-worldwide), and also provided some demo decks (https://github.com/microsoft/mdatp-devicecontrol/tree/main/Removable%20Storage%20Access%20Control%20Samples/Demo), let me know if you think it is still not clear.
